### ISSUE TITLE
Tez on EMR 4.0.0

### ISSUE THREAD

**Issue by ankurmitujjain** [aws-samples/emr-bootstrap-actions#155]
Hello Team,
Is there any way we can enable tez on Hive at emr 4.0.0.
Thanks
Ankur

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
