### ISSUE TITLE
Impala bootstrap issues on ami 3.8

### ISSUE THREAD

**Issue by amit398** [aws-samples/emr-bootstrap-actions#156]
I am having the following issues using impala bootstrap action to install version 2.2 on emr cluster running on ami 3.8
1. Block tracking and short-circuit reads are not configured in hdfs-site.xml. 

2   Attempt to enable above  by adding hdfs properties fails because impalad is unable to find (or load) libhadoop.so

Log file created at: 2015/08/13 06:45:41
Running on machine: xxxxxxxxx
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0813 06:45:41.168217 23429 logging.cc:119] stderr will be logged to this file.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/impala/lib/impala-frontend-0.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/impala/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
15/08/13 06:45:42 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/08/13 06:45:43 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
1. Impala process keeps restarting every 3 hrs . See below from service-nanny logs

Thu Aug 13 00:44:13 +0000 2015  INFO    Running  ( /home/hadoop/impala/bin/impala-launcher start-impalad ) >> /mnt/var/log/service-nanny/impalad-2015-08-13 2>&1 < /dev/null
Thu Aug 13 00:44:13 +0000 2015  INFO    Waiting for 31395 to terminate
Thu Aug 13 00:44:23 +0000 2015  INFO    Handling SIGCHILD: waiting_pid=31395
Thu Aug 13 00:44:23 +0000 2015  INFO    Finished waiting for 31395 status=0
Thu Aug 13 00:44:23 +0000 2015  INFO    starting impalad
Thu Aug 13 00:44:23 +0000 2015  INFO    Running  ( /home/hadoop/impala/bin/impala-launcher start-impalad ) >> /mnt/var/log/service-nanny/impalad-2015-08-13 2>&1 < /dev/null
Thu Aug 13 00:44:23 +0000 2015  INFO    Waiting for 31421 to terminate
Thu Aug 13 00:44:23 +0000 2015  INFO    Handling SIGCHILD: waiting_pid=31421
Thu Aug 13 00:44:23 +0000 2015  INFO    Finished waiting for 31421 status=0
Thu Aug 13 00:44:23 +0000 2015  INFO    maximum retries reached, giving up for this round
Thu Aug 13 03:44:51 +0000 2015  INFO    starting impalad
Thu Aug 13 03:44:51 +0000 2015  INFO    Running  ( /home/hadoop/impala/bin/impala-launcher start-impalad ) >> /mnt/var/log/service-nanny/impalad-2015-08-13 2>&1 < /dev/null
Thu Aug 13 03:44:51 +0000 2015  INFO    Waiting for 11236 to terminate
Thu Aug 13 03:45:01 +0000 2015  INFO    Handling SIGCHILD: waiting_pid=11236
Thu Aug 13 03:45:01 +0000 2015  INFO    Finished waiting for 11236 status=0
Thu Aug 13 03:45:01 +0000 2015  INFO    starting impalad
Thu Aug 13 03:45:01 +0000 2015  INFO    Running  ( /home/hadoop/impala/bin/impala-launcher start-impalad ) >> /mnt/var/log/service-nanny/impalad-2015-08-13 2>&1 < /dev/null
Thu Aug 13 03:45:01 +0000 2015  INFO    Waiting for 11262 to terminate
Thu Aug 13 03:45:01 +0000 2015  INFO    Handling SIGCHILD: waiting_pid=11262
Thu Aug 13 03:45:01 +0000 2015  INFO    Finished waiting for 11262 status=0
Thu Aug 13 03:45:01 +0000 2015  INFO    maximum retries reached, giving up for this round
Thu Aug 13 06:45:30 +0000 2015  INFO    starting impalad
Thu Aug 13 06:45:30 +0000 2015  INFO    Running  ( /home/hadoop/impala/bin/impala-launcher start-impalad ) >> /mnt/var/log/service-nanny/impalad-2015-08-13 2>&1 < /dev/null
Thu Aug 13 06:45:30 +0000 2015  INFO    Waiting for 23380 to terminate
Thu Aug 13 06:45:40 +0000 2015  INFO    Handling SIGCHILD: waiting_pid=23380
Thu Aug 13 06:45:40 +0000 2015  INFO    Finished waiting for 23380 status=0
Thu Aug 13 06:45:40 +0000 2015  INFO    starting impalad
Thu Aug 13 06:45:40 +0000 2015  INFO    Running  ( /home/hadoop/impala/bin/impala-launcher start-impalad ) >> /mnt/var/log/service-nanny/impalad-2015-08-13 2>&1 < /dev/null

**Comment by mombergm** [comment]
Hi Amit. 
Thanks for letting us know. We are looking into this and will provide you with some feedback as soon as we have solved the problem.

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
