### ISSUE TITLE
Logstash plugins failing to install.

### ISSUE THREAD

**Issue by iallison** [aws-samples/emr-bootstrap-actions#169]
The following command fails when attempting to install a logstash plugin after using the EMR elastic search bootstrap script to install logstash_install.rb.

```
cd ~/logstash/logstash-1.4.2
./bin/plugin install logstash-input-s3
Can only install contrib at this time... Exiting.
```

It appears that the logstash version installed (1.4.2) is not the latest stable version (1.5.3).

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
