### ISSUE TITLE
Impala 2.3 support

### ISSUE THREAD

**Issue by amit398** [aws-samples/emr-bootstrap-actions#179]
@mombergm : Is there a plan to update and provide support for impala 2.3 version. There are some blocker ticket which have been resolved in version 2.3 . e.g https://issues.cloudera.org/browse/IMPALA-2203

  We have been able workaround some of the issues raised in https://github.com/awslabs/emr-bootstrap-actions/issues/156 and use the current BA. It would be great if we could have support for version 2.3  on ami 3.8 or 3.9

**Comment by ankurmitujjain** [comment]
Is there any plan to include latest version on Impala in EMR?

Thanks
Ankur

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
