### ISSUE TITLE
Bootstrap for new Impala

### ISSUE THREAD

**Issue by ankurmitujjain** [aws-samples/emr-bootstrap-actions#184]
Hello Team,

How can we install new version on Impala on EMR?

Thanks
Ankur

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
