### ISSUE TITLE
bootstrapping opentsdb using emr-4.6.0, HBASE_HOME issue 

### ISSUE THREAD

**Issue by mqsquidy** [aws-samples/emr-bootstrap-actions#186]
On EMR cluster with:  "ReleaseLabel": "emr-4.6.0",

start_and_configure_tsd.sh:

HBASE_HOME=/home/hadoop/hbase

needs to be changed to:

HBASE_HOME=/usr/lib/hbase

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
