### ISSUE TITLE
Support Scala 2.11

### ISSUE THREAD

**Issue by ganeshkrishnan1** [aws-samples/emr-bootstrap-actions#187]
Scala 2.11 is no longer experimental and Spark has builds with Scala 2.11
Are there plans for EMR to support Spark with 2.11? 
Perhaps the install-spark script should have option to chose the version of Spark (With 2.10 or 2.11)

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
