### ISSUE TITLE
Installing latest version of Impala on  EMR 

### ISSUE THREAD

**Issue by mrakshay** [aws-samples/emr-bootstrap-actions#193]
Hello,as per my knowledge,last bootstrap script was released for Impala 2.2 on EMR version 3.x.Are there any plans to add latest version of Impala on EMR 4.7 ??

**Comment by naveen-tex** [comment]
Hi Akshay - have you figured out a way to install the latest version on EMR 4.7?

**Comment by mrakshay** [comment]
No...I don't think so there is a way to install latest version on EMR 4.7...I managed to install Impala 2.2 on EMR 4.6 through bootstrap action

**Comment by somr** [comment]
Hi mrakshay, Could you share how did you succeed installing Impala2.2 on EMR 4.7. Just wondering if there's some way to have this done with the latest version of EMR and Impala. Thanks in advance !!!

**Comment by mrakshay** [comment]
https://github.com/awslabs/emr-bootstrap-actions/issues/181

**Comment by somr** [comment]
@mrakshay : Thanks for your update. Doing some tweaks on the source code, I was able to build Impala sources on an EMR instance (5.X.X). 
Then, after fixing some config to suit the EMR config, again editing some scripts adding configuration options and creating some ad-hoc scripts, I was able to have a gz with the Impala binaries and I was able to deploy&run Impala on EMR (5.X.X)  : State-store+catalog on the master and 4 different Task Nodes running impalad.
It's not an straightforward way and it's not easy to maintain (e.g. a new version of Impala source code is appearing) but it's working

**Comment by mrakshay** [comment]
@somr : oh so you installed Impala on EMR 5.x. Are the steps to install on 5.x same as how it was for EMR 4.7 ??

**Comment by somr** [comment]
@mrakshay: Hummmm, I don't think so. I built Impala from the source code because I was unable to run the installed RPMs. 
In order to do that I edited the sc and tweak a little bit some scripts. Please,keep in mind that EMR and the Amazon AMI are not officially supported so I'm not sure if this wow could be used on production systems.

**Comment by mrakshay** [comment]
Ok which version of Impala you installed on EMR 5.x ??

**Comment by somr** [comment]
Well, I was downloading different versions from https://github.com/cloudera/Impala, building the source code (with the tweaks required to be able to build the binaries on a EMR 5.X Master node) and applying the changes to the built. I'm afraid I don't have the latest version I've used.

You can follow the steps on https://cwiki.apache.org/confluence/display/IMPALA/Building+Impala. 
Just edit Impala-cdh5-trunk/bin/bootstrap_toolchain.py and amend the OS_MAPPING  with a new entry like  "amazonami" : "ec2-package-centos-7". This should allow you to compile the code but the test will fail (probably). 
Check the config file core-site.xml under the Impala folders (at $HADOOP_CONF_DIR) and ensure that it has the right congif as per /etc/hadoop/conf/core-site.xml on the EC2 instance.
Once you have this done, you should be able to run an Impala minicluster in a single host (which it would be the EMR Master Node)

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
