### ISSUE TITLE
Permission denied error AMI 3.11.0

### ISSUE THREAD

**Issue by jmsmcniff** [aws-samples/emr-bootstrap-actions#194]
Hello team,

Are there are known issues when installing the latest 2.x version of Impala in AMI 3.11.0? Receiving the following error:

**16/06/21 09:59:12 INFO s3n.S3NativeFileSystem: Opening 's3://support.elasticmapreduce/bootstrap-actions/impala/impala-shell-2.2.0-AMZ.tar.gz' for reading
rm: cannot remove /mnt/tmp/hsperfdata_root/1658: Permission denied
rm: cannot remove /mnt/tmp/hsperfdata_oozie/3973: Permission denied
/mnt/var/lib/bootstrap-actions/4/impala-install:43:in `run': Command failed: rm -rf /mnt/tmp/ (RuntimeError)
    from /mnt/var/lib/bootstrap-actions/4/impala-install:182**

Kind regards,
James.

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
