### ISSUE TITLE
Bootstrap for Apache Kylin

### ISSUE THREAD

**Issue by mkanchwala** [aws-samples/emr-bootstrap-actions#195]
Need a bootstrap action for Apache Kylin OLAP engine on Amazon EMR 4.x

**Comment by shaofengshi** [comment]
hello, anyone works on this? If no, I'd like to take over. Thx!

**Comment by rtjarvis** [comment]
Hey - ever get anywhere with this? I'd be interested!

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
