### ISSUE TITLE
Error downloading file from Amazon S3

### ISSUE THREAD

**Issue by jomach** [aws-samples/emr-bootstrap-actions#197]
Hello Guys, 

Did you fix the problem with the if-run ?  

I still get : 

Attempting to download file 's3://_removed_.sh' 
Error downloading file from Amazon S3

I tried: 
"Args": ["instance.isMaster=true","echo `aws s3 cp s3://datalens-sparkjobserversources/sparkjobserver_deploy.sh . ;bash sparkjobserver_deploy.sh`"]

and 

"ScriptBootstrapAction": {
                      "Path": "s3://elasticmapreduce/bootstrap-actions/run-if",
                      "Args": ["instance.isMaster=true","s3://datalens-sparkjobserversources/sparkjobserver_deploy.sh"]
                    }
                  }]

**Comment by jomach** [comment]
on "ReleaseLabel" : "emr-4.7.1",

**Comment by BDeus** [comment]
It seem that the path "/home/hadoop/bin/hadoop" for copy the s3 file isn't valid anymore since emr 4
Can you change that with "/usr/bin/hadoop" ?

**Comment by Chintanvpatel** [comment]
You can get the correct script from `/usr/share/aws/emr/scripts/run-if` from instance itself. It's getting updated based on releaseLabel.

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
