### ISSUE TITLE
Kafka support on EMR 5.x

### ISSUE THREAD

**Issue by mkanchwala** [aws-samples/emr-bootstrap-actions#200]
Can we have a bootstrap script or new service for Kafka on 5.x.

Thanks

**Comment by fabianmurariu** [comment]
have a look at https://github.com/awslabs/emr-bootstrap-actions/pull/204

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
