### ISSUE TITLE
Reading LZO files from Spark stand alone program

### ISSUE THREAD

**Issue by dibyenduc** [aws-samples/emr-bootstrap-actions#202]
Hi Christopher,

With reference to your following link, I was trying to read LZO files with Spark:

https://github.com/awslabs/emr-bootstrap-actions/blob/master/spark/examples/reading-lzo-files.md

My experience is limited: Though I had had partial success from Spark shell, but my stand alone program did not even compile. I suspect some jar file is required. 

val files = sc.newAPIHadoopFile("s3://support.elasticmapreduce/spark/examples/lzodataindexed/*.lzo", classOf[com.hadoop.mapreduce.LzoTextInputFormat],classOf[org.apache.hadoop.io.LongWritable],classOf[org.apache.hadoop.io.Text]) 

Would you kindly let me know how to do this from a stand alone program? 

Thanks and regards,

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
