### ISSUE TITLE
Installing latest version of Impala on EMR

### ISSUE THREAD

**Issue by mrakshay** [aws-samples/emr-bootstrap-actions#208]
Hello,
Is there any bootstrap script to install Impala 2.5 or version above 2.5 on Amazon EMR ?

Regards,
Akshay

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
