### ISSUE TITLE
Bootstrap for Sentry

### ISSUE THREAD

**Issue by Swalloow** [aws-samples/emr-bootstrap-actions#209]
Hello Team,

How can we install Sentry on EMR?
Is there any other solution?

Thanks.

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
