### ISSUE TITLE
EMR cluster fails at boot strap

### ISSUE THREAD

**Issue by santoshvivan** [aws-samples/emr-bootstrap-actions#218]
Hi Team,

We are trying to create EMR cluster from python script with custom AMI with boot strap action but every-time it failed to create.

But when we perform the same from EMR console (GUI) we are able to create cluster successfully.

We are crating the EMR in private subnet where it successfully created from EMR console but not from python script  

I am using below as my boot strap script
#!/bin/bash
set -o xtrace
pip install boto3
sudo -u root yum install python34 python34-pip -y
**AND** 
#!/bin/bash
set -o xtrace
sudo pip install boto3
sudo -u root yum install python34 python34-pip -y  

![Error](https://user-images.githubusercontent.com/20396276/85025346-e5fc1300-b194-11ea-9b63-cb9151bd1f48.JPG)

Thanks
Santosh Panchal

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
