### ISSUE TITLE
 Bootstrap has execute failed to my shell script file on S3 

### ISSUE THREAD

**Issue by waltzbucks** [aws-samples/emr-bootstrap-actions#220]
Hi.

When I got a make up to EMR Cluster. it has with Bootstrap action put it like this:

    instance.isMaster=true s3://bucketname/bootstrap_action_script.sh

Then has been failed bootstrap action with this error message:

    Master instance (i-0000000000000000) failed attempting to download bootstrap action 1 file from S3

So I've go checked up in Master instances, then I found out bootstrap-action log like that:

    2020-11-20T07:04:05.133Z ERROR Source: BOOTSTRAP_ACTION | ErrorCode: SCRIPT_EXECUTION_FAILED_CODE | Execution for s3://ap-northeast-2.elasticmapreduce/bootstrap-actions/run-if failed with code '1'
    /emr/instance-controller/lib/bootstrap-actions/1/run-if:80:in `exit': no implicit conversion of Process::Status into Integer (TypeError)
        from /emr/instance-controller/lib/bootstrap-actions/1/run-if:80:in `download_and_execute_command'
        from /emr/instance-controller/lib/bootstrap-actions/1/run-if:138:in `<main>'
    Attempting to download file 's3://bucketname/bootstrap_action_script.sh'
    Error downloading file from Amazon S3

That's why, has figured out run-if script. I guess that 77 line 'system("/home/hadoop/bin/hadoop fs -copyToLocal #{command} ./")' process failed on it. so checked that exist binary file "/home/hadoop/bin/hadoop" whether or not on this instance when a while on execute bootstrap process. As I thought, there was no "hadoop" file when does on bootstrarp cation process.

    [root@ip-10-0-2-197 hadoop]# ll /home/hadoop/bin/hadoop 
    ls: cannot access /home/hadoop/bin/hadoop: No such file or directory

I think that need to improvement for this issue.

Thanks

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
